[package]
name = "hft-engine"
version = "0.1.0"
edition = "2021"

[dependencies]
prometheus = "0.13"
lazy_static = "1.4"
tokio = { version = "1.0", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
async-trait = "0.1"
thiserror = "2.0.1"
